const $=id=>document.getElementById(id);let adminChannel=null;
function toast(m){const t=$("toast");t.textContent=m;t.style.display="block";clearTimeout(window.tt);window.tt=setTimeout(()=>t.style.display="none",1800)}
function go(id){document.querySelectorAll(".screen").forEach(x=>x.classList.remove("active"));$(id)?.classList.add("active")}
async function session(){if(!window.KOPI_SUPABASE_READY){toast("Database not connected");return null}let {data:{session}}=await supabase.auth.getSession();if(session)return session;let r=await supabase.auth.signInAnonymously();if(r.error){toast(r.error.message);return null}return r.data.session}
async function enterManagement(){if(!$("adminName").value.trim())return toast("Enter your management name");if(!(await session()))return;go("dashboard");refreshAll();subscribe();}
function showTab(tab,btn){["applications","orders","partners"].forEach(x=>$(x+"Tab").classList.toggle("hidden",x!==tab));document.querySelectorAll(".admin-tabs button").forEach(x=>x.classList.remove("active"));btn.classList.add("active")}
async function refreshAll(){await session();await Promise.all([loadStats(),loadApplications(),loadOrders(),loadPartners()])}
async function loadStats(){
 const [ca,ra,c,r,o]=await Promise.all([
  supabase.from("cook_applications").select("id",{count:"exact",head:true}).eq("status","pending"),
  supabase.from("rider_applications").select("id",{count:"exact",head:true}).eq("status","pending"),
  supabase.from("merchants").select("id",{count:"exact",head:true}).eq("status","approved").eq("active",true),
  supabase.from("riders").select("id",{count:"exact",head:true}).eq("status","approved").eq("active",true),
  supabase.from("orders").select("id,status,created_at")
 ]);
 $("pendingCooks").textContent=ca.count||0;$("pendingRiders").textContent=ra.count||0;$("approvedCooks").textContent=c.count||0;$("approvedRiders").textContent=r.count||0;
 const orders=o.data||[], today=new Date().toISOString().slice(0,10);
 $("activeOrders").textContent=orders.filter(x=>!["delivered","cancelled","declined"].includes(x.status)).length;
 $("todayOrders").textContent=orders.filter(x=>x.created_at?.startsWith(today)).length;
}
async function loadApplications(){
 const [c,r]=await Promise.all([supabase.from("cook_applications").select("*").eq("status","pending").order("created_at",{ascending:false}),supabase.from("rider_applications").select("*").eq("status","pending").order("created_at",{ascending:false})]);
 $("cookApps").innerHTML=c.data?.length?c.data.map(x=>`<div class="admin-card"><b>${esc(x.display_name||x.full_name)}</b><small>${esc(x.full_name)} · ${esc(x.phone)}</small><small>${esc(x.food_type||"Cook")} · Capacity ${x.daily_capacity||"--"} pax</small><div class="card-actions"><button class="green" onclick="approveCook('${x.id}')">APPROVE</button><button class="decline" onclick="rejectApp('cook_applications','${x.id}')">REJECT</button></div></div>`).join(""):"<div class='empty-state'>No pending cook applications.</div>";
 $("riderApps").innerHTML=r.data?.length?r.data.map(x=>`<div class="admin-card"><b>${esc(x.full_name)}</b><small>${esc(x.phone)} · ${esc(x.vehicle_type||"Rider")}</small><small>Area: ${esc(x.operating_area||"--")}</small><div class="card-actions"><button class="green" onclick="approveRider('${x.id}')">APPROVE</button><button class="decline" onclick="rejectApp('rider_applications','${x.id}')">REJECT</button></div></div>`).join(""):"<div class='empty-state'>No pending rider applications.</div>";
}
async function approveCook(id){const {data:a,error}=await supabase.from("cook_applications").select("*").eq("id",id).single();if(error)return toast(error.message);const {error:e}=await supabase.from("merchants").insert({name:a.display_name||a.full_name,type:a.food_type||"Local Food",bio:a.bio||"",operating_start:a.operating_start,operating_end:a.operating_end,order_open:a.operating_start,order_close:a.operating_end,daily_capacity:a.daily_capacity||20,status:"approved",active:true,menu_live:true});if(e)return toast(e.message);await supabase.from("cook_applications").update({status:"approved",approved_at:new Date().toISOString()}).eq("id",id);toast("Cook approved ✓");refreshAll()}
async function approveRider(id){const {data:a,error}=await supabase.from("rider_applications").select("*").eq("id",id).single();if(error)return toast(error.message);const {error:e}=await supabase.from("riders").insert({name:a.full_name,phone:a.phone,vehicle_type:a.vehicle_type,operating_area:a.operating_area,status:"approved",active:true});if(e)return toast(e.message);await supabase.from("rider_applications").update({status:"approved",approved_at:new Date().toISOString()}).eq("id",id);toast("Rider approved ✓");refreshAll()}
async function rejectApp(table,id){if(!confirm("Reject this application?"))return;await supabase.from(table).update({status:"rejected",rejected_at:new Date().toISOString()}).eq("id",id);toast("Application rejected");refreshAll()}
async function loadOrders(){const {data}=await supabase.from("orders").select("*").order("created_at",{ascending:false}).limit(50);$("orders").innerHTML=data?.length?data.map(o=>`<div class="admin-card"><b>${esc(o.order_number)}</b><span class="status-pill ${o.status}">${esc(o.status)}</span><small>Cook: ${esc(o.merchant_name||o.merchant_id||"--")}</small><small>Rider: ${esc(o.rider_name||"Not assigned")}</small><small>Total: S$${Number(o.total||0).toFixed(2)}</small><small>${o.created_at?new Date(o.created_at).toLocaleString():""}</small></div>`).join(""):"<div class='empty-state'>No orders yet.</div>"}
async function loadPartners(){const [c,r]=await Promise.all([supabase.from("merchants").select("*").eq("status","approved").order("name"),supabase.from("riders").select("*").eq("status","approved").order("name")]);$("cookPartners").innerHTML=c.data?.length?c.data.map(x=>`<div class="partner-row"><span>👨‍🍳</span><div><b>${esc(x.name)}</b><small>${esc(x.type||"Cook")} · ${x.active?"Active":"Inactive"}</small></div><button class="pause" onclick="togglePartner('merchants','${x.id}',${!x.active})">${x.active?"Disable":"Enable"}</button></div>`).join(""):"<div class='empty-state'>No approved cooks.</div>";$("riderPartners").innerHTML=r.data?.length?r.data.map(x=>`<div class="partner-row"><span>🛵</span><div><b>${esc(x.name)}</b><small>${esc(x.vehicle_type||"Rider")} · ${esc(x.operating_area||"--")}</small></div><button class="pause" onclick="togglePartner('riders','${x.id}',${!x.active})">${x.active?"Disable":"Enable"}</button></div>`).join(""):"<div class='empty-state'>No approved riders.</div>"}
async function togglePartner(table,id,active){await supabase.from(table).update({active}).eq("id",id);refreshAll();toast(active?"Partner enabled":"Partner disabled")}
function subscribe(){if(adminChannel)supabase.removeChannel(adminChannel);adminChannel=supabase.channel("management-live").on("postgres_changes",{event:"*",schema:"public",table:"cook_applications"},refreshAll).on("postgres_changes",{event:"*",schema:"public",table:"rider_applications"},refreshAll).on("postgres_changes",{event:"*",schema:"public",table:"orders"},refreshAll).subscribe()}
function esc(s){return String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}


/* Kopi Boy authentication foundation */
window.KB_AUTH_CONFIG={appRole:document.body?.dataset?.app||"unknown",socialProviders:["google","facebook"],phoneOtpReady:false};
function kbAuthReady(){return window.KOPI_SUPABASE_READY&&typeof supabase!=="undefined";}
function kbOpenAuth(title){const o=document.getElementById("kbAuthOverlay");if(!o)return;document.getElementById("kbAuthTitle").textContent=title||"Sign in to Kopi Boy";o.classList.remove("hidden");}
function kbCloseAuth(){document.getElementById("kbAuthOverlay")?.classList.add("hidden");}
async function kbSignIn(provider){if(!kbAuthReady())return toast?.("Kopi Boy database is not connected");const redirectTo=window.location.origin+window.location.pathname;const {error}=await supabase.auth.signInWithOAuth({provider,options:{redirectTo}});if(error)toast?.(error.message);}
function kbPhoneStart(){document.getElementById("kbPhoneArea")?.classList.remove("hidden");}
async function kbSendOtp(){if(!KB_AUTH_CONFIG.phoneOtpReady)return toast?.("Phone OTP will be enabled before public launch.");const phone=document.getElementById("kbPhone")?.value?.trim();if(!phone)return toast?.("Enter your phone number");const {error}=await supabase.auth.signInWithOtp({phone});if(error)return toast?.(error.message);document.getElementById("kbOtp")?.classList.remove("hidden");document.getElementById("kbVerifyBtn")?.classList.remove("hidden");toast?.("OTP sent");}
async function kbVerifyOtp(){const phone=document.getElementById("kbPhone")?.value?.trim(),token=document.getElementById("kbOtp")?.value?.trim();if(!phone||!token)return toast?.("Enter the phone number and OTP");const {error}=await supabase.auth.verifyOtp({phone,token,type:"sms"});if(error)return toast?.(error.message);kbCloseAuth();toast?.("Verified ✓");}
async function kbGetUser(){if(!kbAuthReady())return null;const {data:{user}}=await supabase.auth.getUser();return user||null;}
